apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springapp-service-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: "/actuator/prometheus"