apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: loan-calculator
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: 5432
      name: postgres