version: "3"

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - 8080:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    volumes:
      - app-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  app-db-data:

