version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    build:
      context: .
      dockerfile: db.dockerfile
    image: postgres:14.7-bullseye
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
    restart: always


