backend:
  image:
    repository: destinytm/springapp-backend
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: NodePort
    port: 8080
db:
  image:
    repository: destinytm/springapp-db
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: ClusterIP
    port: 5432
