backend:
  image:
    repository: destinytm/springapp-backend
    pullPolicy: Always
    tag: latest
  service:
    type: NodePort
    port: 8080
db:
  image:
    repository: destinytm/springapp-db
    pullPolicy: Always
    tag: latest
  service:
    type: ClusterIP
    port: 5432
frontend:
  image:
    repository: destinytm/springapp-frontend
    pullPolicy: Always
    tag: latest
  service:
    type: NodePort
    port: 3000

ingress:
  host: test.spring
